print("\nHi, wait a second, everything will be set up in just a second...\n")
shell.run("mkdir Display")
shell.run("cd Display")
shell.run("wget https://raw.githubusercontent.com/K3vinb5/Display/main/main/display.lua")
shell.run("cd ..")
shell.run("wget https://raw.githubusercontent.com/K3vinb5/Display/main/main/setupDisplay.lua")
shell.run("wget https://raw.githubusercontent.com/K3vinb5/Display/main/install/startup.lua")
print("\nEverything's ready, thanks for waiting!")