print("\nHi, wait a second, everything will be set up in just a second...\n")
shell.run("mkdir Display")
shell.run("cd Display")
shell.run("pastebin get JDZfTn6d display.lua")
shell.run("pastebin get JbUmxg4U setup.lua")
shell.run("cd ..")
shell.run("pastebin get 5zqzx8tX startup.lua")
print("\nEverything's ready, thanks for waiting!")