print("\nHi, wait a second, everything will be set up in just a second...\n")
shell.run("wget run https://github.com/9551-Dev/Gui-h/raw/main/installer.lua")
shell.run("mkdir Display")
shell.run("cd Display")
shell.run("pastebin get JDZfTn6d display.lua")
shell.run("pastebin get JbUmxg4U auto.lua")
shell.run("cd ..")
shell.run("pastebin get 5zqzx8tX startup.lua")
print("\nEverything's ready, thanks for waiting!")